# Generated by Django 5.1 on 2024-08-17 10:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('Pcs', 'Pieces'), ('Pcs', 'Pieces'), ('Pcs', 'Pieces')], max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('branch', models.CharField(choices=[('A', 'PRODUCTION A'), ('B', 'PRODUCTION B'), ('C', 'PRODUCTION C')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplypc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_date', models.DateTimeField(default=datetime.datetime(2024, 8, 17, 18, 50, 3, 74464))),
                ('quantity', models.PositiveBigIntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsPieces.productpc')),
            ],
        ),
    ]
