# Generated by Django 5.1 on 2024-08-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsPieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplypc',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 18, 50, 38, 494134)),
        ),
    ]
