# Generated by Django 5.1 on 2024-08-17 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsPieces', '0002_alter_supplypc_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplypc',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 19, 36, 36, 440564)),
        ),
    ]
